steps:
- name: 'gcr.io/$PROJECT_ID/npm'
  args: ['install']
- name: 'gcr.io/$PROJECT_ID/npm'
  args: ['test']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/$REPO_NAME:latest', '.']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME']
